### ISSUE TITLE
Operational problem

### ISSUE THREAD

**Issue by nobodyplayer** [carrtesy/M2N2#1]
Hello, thank you for your excellent work. But I don't know how to run it. Can you give me a requirements? How do I start it after I've done it?

**Comment by carrtesy** [comment]
Hello, thanks for your attention in our work.
No specific requirements are needed for torch/numpy and other DL/ML related frameworks.
For experiments, you need to install hydra (for running with multiple configurations) and wandb (for tracking exps.) 
For starting, you may check scripts directory.

Sincerely,
Carrtesy.
